// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonArrowLeft: typeof import('~icons/carbon/arrow-left')['default']
    CarbonArrowRight: typeof import('~icons/carbon/arrow-right')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPlayFilledAlt: typeof import('~icons/carbon/play-filled-alt')['default']
    CarbonSearch: typeof import('~icons/carbon/search')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    MdiLightArrowUp: typeof import('~icons/mdi-light/arrow-up')['default']
    MdiLightMenu: typeof import('~icons/mdi-light/menu')['default']
    README: typeof import('./components/README.md')['default']
    UimBag: typeof import('~icons/uim/bag')['default']
    UimUserNurse: typeof import('~icons/uim/user-nurse')['default']
  }
}

export { }
